language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'

jdk:
  - oraclejdk7

script:
  ./gradlew assembleDebug testDebug assembleRelease

cache:
  directories:
    - $HOME/.m2
